### ISSUE TITLE
Integrating "external git content" into this package

### ISSUE THREAD

**Issue by BSchilperoort** [TeachBooks/TeachBooks#58]
I was looking into the external content feature again, where we want to add external content to TeachBooks using github/gitlab links.

The TOC would be formatted like;
```yaml
format: jb-book
root: intro.md

parts:
  - caption: Contents
    chapters:
    - file: some_content/overview.md
      sections:
      - file: some_content/text_and_code.ipynb
    - external: https://gitlab.tudelft.nl/interactivetextbooks-citg/risk-and-reliability/-/blob/v0.1/book/intro.md
```

And our scripts would:

-  parse this out
- do git checkouts of the specific tag (full repo, detached HEAD, into a temporary folder)
- put the right local path into a new table of contents
- write the new TOC to file

I tried to see if I can make this a sphinx plugin, but the table of contents is parsed very early, before it reaches the plugins, which is why I now believe putting it inside the teachbooks package is the right location.

It seems to me that putting the functionality here (before the release/publish yaml cleaning) would be the right spot;
https://github.com/TeachBooks/TeachBooks/blob/74e09681cf9516a066cdb153f35178d6dec50452/teachbooks/cli/main.py#L34

Any thoughts @rlanzafame @Tom-van-Woudenberg ?
